name: Build and Release

on:
  push:
    branches:
      - '**'     # all branches
    tags:
      - 'v*.*.*' # version tags
  pull_request:
    branches:
      - '**' 
permissions:
  contents: write

jobs:
  test-build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.8'

      - name: Run unit tests
        run: |
          cd client
          make test
        env:
          CGO_ENABLED: 0

      - name: Build server binary
        run: |
          PROGRAM_NAME=server make linux_static -f build.mk

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'
          channel: 'stable'
        run:
          cd flutter_client
          make linux

#      - name: Build client binary
#        run: |
#          PROGRAM_NAME=client make linux_static -f build.mk
#          PROGRAM_NAME=client make windows -f build.mk

      - name: List build outputs
        run: |
          ls -lh server/build/
          ls -lh client/build/

      - name: Create GitHub Release (only on tags)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: |
            server/build/server
            client/build/client
            client/build/client.exe
            flutter_client/linux/x64/release/bundle/meow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}